export const GET_CONTENT= "GET_CONTENT";
export const ADD_CONTENT= "ADD_CONTENT";
export const UPDATE_CONTENT= "UPDATE_CONTENT";
export const DELETE_CONTENT= "DELETE_CONTENT";
export const READ_CONTENT= "READ_CONTENT";

// for filter

export const TOGGLE_CATEGORY = "TOGGLE_CATEGORY";
export const TOGGLE_FIRST_UPLOAD = "TOGGLE_FIRST_UPLOAD";